config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new' # => root_path
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'users/new'

  get 'tasks/index'
  post 'tasks/create'
  get 'tasks/show'
  get 'tasks/edit'
  patch 'tasks/update'
  get  '/signup',  to: 'users#new'
  resources :users
  resources :tasks


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
	self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
	belongs_to :user
	delegate :name, :to => :user, :prefix => true
	validates :user_id, presence:true
	validates :content, presence:true, length: { maximum:140 }
	scope :desc, -> { order("tasks.created_at DESC") }
end

app/models/user.rb
class User < ApplicationRecord
	has_many:tasks, dependent: :destroy
	attr_accessor :remember_token
	before_save {self.email = self.email.downcase }
	validates :name, presence:true,length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, presence:true, length: { minimum: 6 }, allow_nil:true

	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
		BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end

	def User.new_token
		SecureRandom.urlsafe_base64
	end

	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))
	end

	# 渡されたトークンがダイジェストと一致したらtrueを返す
	def authenticated?(remember_token)
		return false if remember_digest.nil?
		BCrypt::Password.new(remember_digest).is_password?(remember_token)
	end

	def forget
		update_attribute(:remember_digest,nil)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	include SessionsHelper

	private
		# ユーザーのログインを確認するssu
		def logged_in_user
			unless logged_in?
				# store_location
				flash[:danger] = "Please log in."
				redirect_to login_url
			end
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def create
		user = User.find_by(email: params[:session][:email])
	# has_secure_passwordの機能
		if user && user.authenticate(params[:session][:password])
			log_in user
			params[:session][:remember_me] == '1' ? remember(user) : forget(user)
			redirect_to userr
		else
			flash.now[:danger] = "正しいログインIDとパスワードを入力してください"
			render 'new'
		end
	end

	def destroy
		log_out if logged_in?
		redirect_to root_url
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def help
	end

	def about
	end

	def contact
	# app/views/static_pages/contact.html.erb'
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

	before_action :logged_in_user, only: [:create, :destroy]
	before_action :corretct_user, only: [:edit, :update, :destroy]

	def index
	end

	def show
		@task = Task.find(params[:id])
	end

	def create
		@task = current_user.tasks.build(task_params)
		if @task.save
			flash[:success] = "タスクを作成しましたaaaa"
			redirect_to current_user
		else
			flash[:danger] = "タスク内容を入力してください"
			redirect_to current_user
		end
	end


	def edit
	end

	def update
		if @task.update_attributes(task_params)
			flash[:success] = "タスクを更新しました"
			redirect_to current_user
		else
			render 'edit'
		end
	end

	def destroy
		@task.destroy
		flash[:success] = "タスクを削除しました"
		redirect_to request.referrer || current_user
	end

	private

		def task_params
			params.require(:task).permit(:content)
		end

		def corretct_user
			@task = current_user.tasks.find_by(id: params[:id])
			redirect_to current_user if @task.nil?
		end
end

app/controllers/user_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def show
		@user = User.find(params[:id])
		@task = @user.tasks.build
		@tasks = @user.tasks.desc.page(params[:page])
	end

	def create
		@user = User.new(user_params)
		if @user.save
			flash.now[:success] = "welcome!"
			log_in @user
			redirect_to @user
		else
			render 'new'
		end

	end

	private
  
		def user_params
			params.require(:user).permit(:name,:email,:password,:password_confirmation)
		end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def show
		@user = User.find(params[:id])
		@task = @user.tasks.build
		@tasks = @user.tasks.desc.page(params[:page])
	end

	def create
		@user = User.new(user_params)
		if @user.save
			flash.now[:success] = "welcome!"
			log_in @user
			redirect_to @user
		else
			render 'new'
		end

	end

	private

		def user_params
			params.require(:user).permit(:name,:email,:password,:password_confirmation)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
		if (user_id = session[:user_id])
			@current_user ||= User.find_by(id: user_id)
		elsif (user_id = cookies.signed[:user_id])
			user = User.find_by(id: user_id)
			if user && user.authenticated?(cookies[:remember_token])
				#sessionに保存
				log_in user
				@current_user = user
			end
		end
	end

	def logged_in?
		!current_user.nil?
	end

	def remember(user)
		user.remember
		cookies.permanent[:remember_token] = user.remember_token
		cookies.permanent.signed[:user_id] = user.id

	end

	def forget(user)
		user.forget
		cookies.delete(:remember_token)
		cookies.delete(:user_id)
	end

	def log_out
		forget(current_user)
		session.delete(:user_id)
		@current_user = nil
	end

	def current_user?(user)
		user == current_user
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<%= link_to "タスク管理システム", '#', id: "logo" %>
		<nav>
			<ul class="nav navbar-nav navbar-right">         
				<li><%= link_to 'サインアップ', new_user_path %></li>
				<% if logged_in? %>
				<li><%= link_to "ログアウト", logout_path , method: :delete %></li>
				<% else %>
				<li><%= link_to "ログイン", login_path %></li>
				<% end %>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>	
	<%= csrf_meta_tags %>
	<%= stylesheet_link_tag'application', media: 'all',
	'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application',
	'data-turbolinks-track': 'reload' %>
	<!--[if lt IE 9]>
    	<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    	</script>
	<![endif]-->
	<%= favicon_link_tag('/favicon.ico') %>
</head>
<body>
	<%= render 'layouts/header' %>
	<% flash.each do |message_type, message| %>
		<div class="alert alert-<%= message_type %>"><%= message %></div>
	<% end %>
	<div class="container">
		<%= yield %>
	</div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger">
			The form contains <%= pluralize(object.errors.count, "error") %>.
		</div>
		<ul>
			<% object.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
	<ol class="microposts">
		<%= render @feed_items %>
	</ol>
	<%= paginate @feed_items %>
<% end %>

app/views/shared/_task_form.html.erb
<%= form_for(@task) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
	<div class="field">
		<%= f.label :content %>
		<%= f.text_area :content, placeholder: "タスクを入力してください"%>
	</div>
	<%= f.submit "登録する", class: "btn btn-primary" %>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>

<h1>About</h1>
<p>
	The <a href="http://railstutorial.jp/"><em>Ruby on Rails Tutorial</em></a>
	is a <a href="http://railstutorial.jp/book">book</a> and
	<a href="http://screencasts.railstutorial.org/">screencast series</a>
	to teach web development with
	<a href="http://rubyonrails.org/">Ruby on Rails</a>.
	This is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>

<h1>Contact</h1>
<p>
	Contact the Ruby on Rails Tutorial about the sample app at the
	<a href="http://railstutorial.jp/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>

<h1>Help</h1>
<p>
	Get help on the Ruby on Rails Tutorial at the
	<a href="http://railstutorial.jp/help">Rails Tutorial help page</a>.
	To get help on this sample app, see the
	<a href="http://railstutorial.jp/book"><em>Ruby on Rails Tutorial</em>
	book</a>.
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
	<div class="row">
		<aside class="col-md-4">
			<section class="user_info">
			</section>
			<section class="micropost_form">
				<%= render :partial => 'shared/task_form' , :locals => { :object => @user} %>
			</section>
		</aside>
		<div class="col-md-8">
			<h3>Task Feed</h3>
			<%= render 'shared/feed' %>
		</div>
	</div>
<% end %>

app/views/tasks/_task.html.erb
<% if current_user?(task.user) %>
	<li id="micropost-<%= task.id %>">
		<span class="content"><%= link_to task.content,task_path(task) %></span>
		<span class="timestamp"><%= time_ago_in_words(task.created_at) %> ago.</span>
		<span class="operate">
			<%= link_to "編集する",edit_task_path(task.id) %>
			<%= link_to "削除する",task,method: :delete,data:{ confirm: "削除しますか?"} %>
		</span>
		<span class="user">投稿者：<%= link_to task.user_name , user_path(task.user) %></span>
	</li>
<% end %>

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/tasks/edit.html.erb
<h1>タスク編集画面</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@task) do |f| %>
		<%= render 'shared/error_messages' , object:f.object %>

			<%= f.label :content %>
			<%= f.text_field :content, class: 'form-control' %>

			<%= f.submit "更新する", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/tasks/index.html.erb
<h1>Tasks#index</h1>
<p>Find me in app/views/tasks/index.html.erb</p>

app/views/tasks/show.html.erb
<h1>タスク詳細画面</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@task) do |f| %>
			<%= f.label :content %>
			<%= f.text_field :content, class: 'form-control',:readonly => true %>
		<% end %>
		<div class="col-md-6 col-md-offset-5" ><%= link_to "一覧へ戻る",user_path(@task.user) %></div>
	</div>
</div>

app/views/users/new.html.erb
<h1>サインアップ</h1>

<%= form_for(@user) do |f| %>
<%= render :partial => "shared/error_messages",:locals => { :object => @user} %>

	<%= f.label :name %>
	<%= f.text_field :name,class:'form-control' %>

	<%= f.label :email %>
	<%= f.email_field :email,class:'form-control' %>

	<%= f.label :password %>
	<%= f.password_field :password,class:'form-control' %>

	<%= f.label :password, "Confirmation" %>
	<%= f.password_field :password,class:'form-control'  %>

	<%= f.submit "アカウント作成",class:"btn btn-primary" %>
<% end %>

app/views/users/show.html.erb
<div class="row">
	<aside class="col-md-4">
		<section class="user_info">
			<% if current_user?(@user) %>
				<h1><%= @user.name %>さん、こんにちは！</h1>
			<% else %>
				<h1><%= @user.name %>さんのページです</h1>
			<% end %>
		</section>
	</aside>

	<% if current_user?(@user) %>
		<div class="col-md-8">
			<% if @user.tasks.any? %>
				<h3>タスクは現在<%= @user.tasks.count %>個登録中です。</h3>
				<ol class="microposts">
					<%= render @tasks %>
				</ol>
				<%= paginate @tasks %>
			<% end %>
		</div>
		<div class="row">
			<aside class="col-md-4">
				<section class="micropost_form">
					<%= render :partial => 'shared/task_form' , :locals => { :object => @user} %>
				</section>
			</aside>
		</div>
	<% end %>
</div>